name: Deploy to App Store

on:
  push:
    branches: [ 'release/*' ]
  workflow_dispatch:

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[release]') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy-shared.yml
    with:
      environment: 'App Store'
      fastlane_lane: 'release'
    secrets:
      FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
      FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
